# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: build and run tests
          command: xcodebuild test -scheme UnitTestAllModules -destination 'platform=iOS Simulator,name=iPhone 14'
      
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test:
    jobs:
      - build-and-test
